import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./scss/globals.scss";
import Header from "@/src/components/default/header/Header";
import type { Viewport } from "next";
import Footer from "@/src/components/default/footer/Footer";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
};

export const metadata: Metadata = {
  title: "tripusers.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
